<#
.SYNOPSIS
Builds and runs the DDS Viewer test suite.

.DESCRIPTION
Convenience wrapper around CMake build and CTest. On Windows it defaults to the
Visual Studio 2022 build tree generated by generate-build-files.ps1 and runs the
Release config to avoid requiring the MSVC debug runtime outside a developer
environment.

.PARAMETER BuildDir
CMake build directory to use.
Default: build/vs2022 on Windows when present, otherwise build.

.PARAMETER Config
CMake configuration to build and test.
Default: Release.

.PARAMETER NoBuild
Skips the build step and only runs CTest.

.PARAMETER Generate
Runs generate-build-files.ps1 first if the build directory does not exist.

.PARAMETER TestRegex
Optional CTest regex used to run a subset of tests.

.PARAMETER ExtraCTestArgs
Additional arguments forwarded directly to ctest.

.EXAMPLE
./run-tests.ps1
Builds Release and runs all tests.

.EXAMPLE
./run-tests.ps1 -TestRegex DDSLoader
Runs only tests with names matching DDSLoader.

.EXAMPLE
./run-tests.ps1 -BuildDir cmake-build-release -NoBuild
Runs tests from an existing build directory without rebuilding.
#>
param(
    [string]$BuildDir,
    [string]$Config = "Release",
    [switch]$NoBuild,
    [switch]$Generate,
    [string]$TestRegex,
    [string[]]$ExtraCTestArgs = @()
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$runningOnWindows = $PSVersionTable.PSVersion.Major -lt 6 -or $IsWindows

if (-not $BuildDir) {
    if ($runningOnWindows -and (Test-Path -Path "build/vs2022" -PathType Container)) {
        $BuildDir = "build/vs2022"
    }
    else {
        $BuildDir = "build"
    }
}

if ($Generate -and -not (Test-Path -Path $BuildDir -PathType Container)) {
    if (-not (Test-Path -Path "./generate-build-files.ps1" -PathType Leaf)) {
        throw "Cannot generate build files because generate-build-files.ps1 was not found."
    }

    if ($runningOnWindows) {
        & ./generate-build-files.ps1 -Target windows -SkipVs2026
    }
    else {
        & ./generate-build-files.ps1 -Target unix
    }

    if ($LASTEXITCODE -ne 0) {
        throw "Build-file generation failed with exit code $LASTEXITCODE."
    }
}

if (-not (Test-Path -Path $BuildDir -PathType Container)) {
    throw "Build directory '$BuildDir' does not exist. Configure first, or rerun with -Generate."
}

if (-not $NoBuild) {
    Write-Host "Building tests: $BuildDir ($Config)"
    $buildArgs = @("--build", $BuildDir)
    if ($Config) {
        $buildArgs += @("--config", $Config)
    }

    & cmake @buildArgs
    if ($LASTEXITCODE -ne 0) {
        throw "Build failed with exit code $LASTEXITCODE."
    }
}

Write-Host "Running tests: $BuildDir ($Config)"
$ctestArgs = @("--test-dir", $BuildDir, "--output-on-failure")
if ($Config) {
    $ctestArgs += @("-C", $Config)
}
if ($TestRegex) {
    $ctestArgs += @("-R", $TestRegex)
}
if ($ExtraCTestArgs.Count -gt 0) {
    $ctestArgs += $ExtraCTestArgs
}

& ctest @ctestArgs
if ($LASTEXITCODE -ne 0) {
    throw "Tests failed with exit code $LASTEXITCODE."
}
